// <auto-generated />
namespace Go_Parking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class correcao2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(correcao2));
        
        string IMigrationMetadata.Id
        {
            get { return "201805210015263_correcao2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
